---
name: "Trilium Notes"
version: "1.0.2"
slug: "trilium_notes"
description: "Self-hosted hierarchical note-taking application with note versioning, encryption, note attributes and more."
url: "https://github.com/malyem/trilium-notes-home-assistant-addon"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: true
host_network: false
webui: "http://[HOST]:[PORT:8080]/"
ports:
  8080/tcp: 8087
ports_description:
  8080/tcp: "Trilium Notes web interface"
options:
  user_uid: 1000
  user_gid: 1000
schema:
  user_uid: "int(1,)"
  user_gid: "int(1,)"
